### ISSUE TITLE
Is it interruptible?

### ISSUE THREAD

**Issue by eonist** [satoshin21/Anima#1]
Is it interruptible?

**Comment by satoshin21** [comment]
@eonist 
Yes, Anima has method `Anima.pause()` and `Anima.resume()`!
But If you call `pause()`, current animation is not interrupted immediately. 

`pause()` methos will set `Status.willPaused` to `Anima.status`.
Then, current animation will complete but nothing beyond that will be executed. 
to resume in a paused state, call the `resume()` method on Anima.

Anima's example application has sample of `resume()` and `pause()` method , you can try it!

**Comment by eonist** [comment]
More like is it Interactive? Does interactions reflect in the animation immediately? Thx

**Comment by satoshin21** [comment]
It is not refrected immediately.
This method pause after running one of chained animation is completed.

**Comment by eonist** [comment]
Thx. Ill check it out.
