### ISSUE TITLE
How to add a delay?

### ISSUE THREAD

**Issue by ian-bradbury** [satoshin21/Anima#10]
I would like to animate + delay + animate.

Could you provide an example of how to introduce a short delay between animation steps?

Many thanks!
Love the library.

**Comment by satoshin21** [comment]
@ianbradbury-bizzibody 
Thank you for your comment!
Please use `.then(waitFor: TimeInterval)` method like below.

```swift
animaView.layer.anima
            .then(.moveByY(50))
            .then(waitFor: 0.5)      // wait half second
            .then(.moveByX(50))
            .fire()
```

**Comment by ian-bradbury** [comment]
👍 That's great.  Thanks @satoshin21 

I'm annoyed I didn't figure that our myself.  Keep up the great work!
