### ISSUE TITLE
Not working in Xcode 10

### ISSUE THREAD

**Issue by lennycampino** [satoshin21/Anima#7]
Converting non-escaping value to 'T' may allow it to escape on line 57 in AnimaUtility.swift

**Comment by filipeleal** [comment]
I’m having the same problem.

**Comment by satoshin21** [comment]
Thank you for your issue!
I will update Anima today.

**Comment by satoshin21** [comment]
https://github.com/satoshin21/Anima/pull/8

**Comment by satoshin21** [comment]
@lennycampino @filipeleal 
please update your `Podfile` and `pod update` like this.

```
# pod "Anima": "0.8.0"
# ↓
pod "Anima": "0.9.0"
```

It will work on Swift 4.2 😁

**Comment by lennycampino** [comment]
Great, thank you!
